### ISSUE TITLE
No option to enter reader view

### ISSUE THREAD

**Issue by alvin-leong** [Ascrod/readerview#13]
Hi Ascrod,
Thanks for this, I cannot seem to get it work though.  There is no option to enter Reader View even after I installed it.
![extension installed but no option](https://user-images.githubusercontent.com/33982759/33640053-490fcf3c-da69-11e7-9c21-d8edbe9b25e8.png)

**Comment by Ascrod** [comment]
Thanks for the feedback. This is most likely a combination of two issues: #8, which should be resolved with 78d7c33efd6971a8f3561681f0514bc340602639, and #10, which should be fixed very soon. For now, if you go to the customize toolbars menu, you should be able to add the reader button from there.

**Comment by Ascrod** [comment]
This should now be fixed with #10.
