### ISSUE TITLE
Improve shortcut configuration for international keyboard layouts

### ISSUE THREAD

**Issue by Ascrod** [Ascrod/readerview#14]
Default Ctrl+Alt+R shortcut may be problematic or unusable for certain keyboard layouts, such as AltGr. Possibly provide an option to configure or disable the shortcut in about:config.

**Comment by sergeevabc** [comment]
Dear @Ascrod, Ctrl+Alt+R is [used][1] to restart the browser as well, so could you be so kind to accelerate implementing an option to customize the shorcut? Being an avid reader, I am in pain right now.

[1]: https://github.com/MoonchildProductions/Pale-Moon/issues/1490#issuecomment-347161508

**Comment by Ascrod** [comment]
This issue is specifically about improving compatibility with international keyboard layouts. I have no control over what other extensions decide to use for their own shortcuts or whether people use extensions that have conflicting shortcut keys.

I have looked into making the shortcut configurable, but doing so will require a lot of additional overhead and a new UI for configuring the key. For the time being, it would probably be simpler to add an option to about:config for disabling the shortcut.

**Comment by Ascrod** [comment]
Added a preference to disable the shortcut key: b7eed443426e9d34274135ac8f3734d892b4fe01. Again, this may be made more configurable in the future, but for now I am marking this issue as resolved.

**Comment by sergeevabc** [comment]
Take a peep at the code of [Fox Input][1] extension, which binds Alt+J layout independently.

[1]: https://addons.mozilla.org/en-US/firefox/addon/fox-input/versions/0.5.5.1-signed.1-signed
