### ISSUE TITLE
Moved other buttons

### ISSUE THREAD

**Issue by grumpygeek** [Ascrod/readerview#18]
It caused some buttons to move to far left (I had arrows, reload etc on right), and some were dropped into Customize palette.  I did not try and trace any exact cause, just reverted to a profile backup.  I realize this info is not of much use, sorry.

**Comment by Ascrod** [comment]
Got a few reports of this on the forum. I'm reverting 3fb4985018a99fbce83ab13ac0320f72436a719f and releasing a new version until I have more time to troubleshoot this.

**Comment by grumpygeek** [comment]
I think the customize menu may be caused by some other extension (actually can't find out what is causing it).  So I edited the title and first post for this.

**Comment by Ascrod** [comment]
Have done some testing on this, and I think it just comes down to how each extension (or the browser) positions its buttons on application startup. It can be a messy system, and sometimes they just don't always play nicely with each other. I especially noticed this with some restartless add-on buttons.

Fortunately, If you do see this happen after installing Reader View, it should only be a one-time event. You will have to rearrange your UI once before it sticks, and it should stay that way... assuming *other* extensions don't mess with it later.

Once installed, the add-on sets a preference in about:config to remind itself to not to not add the button to the UI again. This preference stays in your browser's config even if you uninstall the extension (as a side effect of how Firefox and derivative browsers handle extension preferences). So as long as you do not delete or reset that preference manually, you should not see your UI change again, even if you uninstall and reinstall later.

HTH. I've commited 051aa3b226a0a1cadd358f4775fd41926da36611 to reintroduce this functionality, and it should be a bit more stable now. I'll do some more testing and will probably release 1.0.2 tomorrow.

**Comment by grumpygeek** [comment]
Worked nicely this time, inserted just after url box.
