### ISSUE TITLE
Text size

### ISSUE THREAD

**Issue by rn2208** [Ascrod/readerview#41]
The text size buttons have stopped working. An example below.

![1](https://user-images.githubusercontent.com/42857944/61960043-29c6b680-afde-11e9-819f-453e907f8a2d.gif)

**Comment by Ascrod** [comment]
This is an issue with custom themes. aboutReader.css was updated in toolkit, and themes will need to be updated to match that change. Please see [this post](https://forum.palemoon.org/viewtopic.php?f=46&t=17660&p=170033#p170017) for more information.

**Comment by rn2208** [comment]
Thanks for the quick response. You saved me a lot of time.
