### ISSUE TITLE
1. Show article dates 2. Remove expected reading time in reader mode

### ISSUE THREAD

**Issue by strabadser** [Ascrod/readerview#42]
I am not a developer and don't understand anything about programming, but I hope this is the right place to post this request. I make extensive use of your Reader View in a  Pale Moon fork called ArcticFox. Is there a way 1. to have the date of the articles show in reader mode (it never does), and 2. less important, remove the expected reading duration (useless to me)?

Thank you, your work and the features added to the old Firefox version are very much appreciated.

RobertJ

**Comment by Ascrod** [comment]
1) Unfortunately this isn't really doable. If the page has a publish date at all, almost every one of them shows it very differently, so it would be difficult for the reader library to extract. (The library is what does all the parsing, and is actually developed by Mozilla, not me.)
2) There isn't currently an option to show or hide the reading duration. The font for it is also quite small, so is there really a need to remove it? Maybe if you use an ad blocker, you might be able to hide the page element that contains the text.

**Comment by strabadser** [comment]
Oh well, thank you anyway, that was kind of you.
