### ISSUE TITLE
Reader mode doesn't seem to work correctly with finance.yahoo.com news articles.

### ISSUE THREAD

**Issue by hmm3** [Ascrod/readerview#43]
E.g. https://finance.yahoo.com/news/marvell-buy-inphi-10-bln-110101936.html

Yet they work fine with firefox's reader mode.

**Comment by hmm3** [comment]
Made a mistake, it doesn't seem to work with firefox either.

**Comment by Ascrod** [comment]
Pale Moon (technically the platform) uses the same parsing engine as Firefox, so if it doesn't work there it's unlikely to work here either.
